# Generated by Django 3.0.8 on 2020-10-03 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_follower_following'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
