# Generated by Django 3.0.8 on 2020-10-03 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_like_postid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='postId',
            new_name='post',
        ),
    ]
